NewBarkTown_MapScripts::
	.byte 0 @ No map scripts currently

NewBarkTown_EventScript_FatMan::
	msgbox NewBarkTown_Text_FatMan, MSGBOX_NPC
	end

NewBarkTown_Text_RivalText1:
	.string "… … …\p"
	.string "So this is the famous ELM POKéMON\n"
	.string "LAB…$"

NewBarkTown_Text_RivalText2:
	.string "…What are you staring at?$"

NewBarkTown_Text_FatMan:
	.string "Yo, {PLAYER}! I hear PROF. ELM\n"
	.string "discovered some new POKéMON.$"

NewBarkTown_Text_GearImpressive:
	.string "Wow, your POKéGEAR is impressive!\n"
	.string "Did your mom get it for you?$"

NewBarkTown_Text_MonIsAdorable:
	.string "Oh! Your POKéMON is adorable!\n"
	.string "I wish I had one!$"

NewBarkTown_Text_TellMomYoureLeaving:
	.string "Hi, {PLAYER}!\n"
	.string "Leaving again?\p"
	.string "You should tell your mom if you're\n"
	.string "leaving town.$"

NewBarkTown_Text_CallMom:
	.string "Call your mom on your POKéGEAR to\n"
	.string "let her know how you're doing.$"

NewBarkTown_Text_WaitPlayer:
	.string "Wait, {PLAYER}!$"

NewBarkTown_Text_WhatDoYouThinkYoureDoing:
	.string "What do you think you're doing?$"

NewBarkTown_Text_ItsDangerousToGoAlone:
	.string "It's dangerous to go out without a\n"
	.string "POKéMON!\p"
	.string "Wild POKéMON jump out of the grass\n"
	.string "on the way to the next town.$"

NewBarkTown_Text_TownSlogan:
	.string "NEW BARK TOWN\n"
	.string "The Town Where the Winds of a\l"
	.string "New Beginning Blow$"

NewBarkTown_Text_ElmLab:
	.string "ELM POKéMON LAB$"

NewBarkTown_Text_PlayersHouse:
	.string "{PLAYER}'s house$"

NewBarkTown_Text_ElmsHouse:
	.string "PROF. ELM'S HOUSE$"
